# ─────────────────────────────────────────────
# tmux
# ─────────────────────────────────────────────



# Shell
set -g default-shell /usr/bin/fish


# General
set -g mouse on
set -g history-limit 10000
set -g focus-events on
set -g escape-time 0
set -as terminal-features ",*:RGB"

# New panes/windows inherit current directory
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"


# ─────────────────────────────────────────────
# Focus
# ─────────────────────────────────────────────

bind -n C-Left  select-pane -L
bind -n C-Right select-pane -R
bind -n C-Up    select-pane -U
bind -n C-Down  select-pane -D


# ─────────────────────────────────────────────
# Move panes
# Ctrl+Shift+Arrow
# ─────────────────────────────────────────────

bind -n C-S-Left  swap-pane -s '{left-of}'
bind -n C-S-Right swap-pane -s '{right-of}'
bind -n C-S-Up    swap-pane -s '{up-of}'
bind -n C-S-Down  swap-pane -s '{down-of}'


# ─────────────────────────────────────────────
# Pane management
# ─────────────────────────────────────────────

# Fullscreen current pane
bind -n C-f resize-pane -Z

# Kill pane
bind -n C-q kill-pane

# Floating terminal
bind -n C-t display-popup -E -w 80% -h 80% \
    -d "#{pane_current_path}"


# ─────────────────────────────────────────────
# tmux/session
# ─────────────────────────────────────────────

# Kill entire tmux server
bind -n C-S-q kill-server


# ─────────────────────────────────────────────
# Config
# ─────────────────────────────────────────────

bind r source-file ~/.config/tmux/tmux.conf \; \
    display-message "tmux config reloaded"


# ─────────────────────────────────────────────
# Status
# ─────────────────────────────────────────────

set -g status-position bottom
set -g status-interval 2

set -g status-left " #S "
set -g status-left-length 30

set -g status-right " #{pane_current_path} "

set -g window-status-format " #I:#W "
set -g window-status-current-format " #I:#W "

set -g pane-border-status off


# ─────────────────────────────────────────────
# Copy mode
# ─────────────────────────────────────────────

setw -g mode-keys vi

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel


# ─────────────────────────────────────────────
# Windows
# ─────────────────────────────────────────────

set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on
